name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: server
        run: |
          npm ci
          npm run lint
          npm run format:check
          npm test

      - name: client
        run: |
          cd client
          npm ci
          npm run lint
          npm run format:check
          npm test

      - name: e2e
        if: github.event_name == 'push'
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3000
          working-directory: client
