name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: server
        run: |
          npm ci
          npm run lint
          npm run format:check

      - name: client
        run: |
          cd client
          npm ci
          npm run build
          npm run lint
          npm run format:check

      - name: deploy
        if: github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'muvee'
          heroku_email: 'rjshekhar.official@gmail.com'
          healthcheck: 'https://muvee.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
